---

- name: installer les paquets nécessaires
  apt: name="ocsinventory-agent" state=present
  become: True

- name: création dossier
  file: name=/etc/ocsinventory state=directory recurse=yes
  become: True

- name: configuration
  copy: src="files/{{ item }}" dest=/etc/ocsinventory/ owner=root group=root mode=0600
  become: True
  with_items:
    - modules.conf
    - ocsinventory-agent.cfg

- name: script vérifiant si le serveur est joignable
  copy: src=files/ocsinventory_runif.sh dest=/usr/local/bin/ owner=root group=root mode=0755
  become: True

#TODO sudo ln -s /home/cedric/bin/public/ocsinventory.sh /etc/cron.hourly/ocsinventory

- name: cron
  copy: src=files/cron dest=/etc/cron.d/ocsinventory-agent owner=root group=root mode=0644
  become: True

- name: nettoyage ancienne cron
  file: path=/etc/cron.daily/ocsinventory-agent state=absent
  become: True
  