---

- name: check version installée
  shell: "aptitude show rambox | grep {{ rambox_version }}"
  failed_when: false
  changed_when: false
  register: out

- name: installation paquet
  apt: 
    deb: "{{ rambox_url }}"
  become: true
  when: out.rc > 0