---
- hosts: localhost
  vars:
    compte: cedric
    basedir: "/home/{{ compte }}"
    basedir_perso: "/home/{{ compte }}"
    module_lang: fr_FR.UTF-8
  roles:
#    - apnees
    - shell_mysql
    - workstation
    - security
