---

- hosts: all
  vars:
    compte: cedric
    basedir: "/home/{{ compte }}"
    module_lang: fr_FR.UTF-8
  roles:
    - { role: mercurial-install, tags: ['mercurial-install'] }

    - { role: etc-init, tags: ['etc-init'] }
    - { role: ubuntu-cleanup, tags: ['ubuntu-cleanup' ] }
    - { role: apt-paquets, tags: ['apt-paquets', 'softs'] }
    - { role: bash-init, tags: ['bash-init' ] }
    - { role: auth-init, tags: ['auth-init'] }
    - { role: apt-init, tags: ['apt-init'] }
    - { role: bash-completion }
    - { role: ssh-auth, tags: ['ssh-auth'] }
    - { role: cron-conf, tags: ['cron-conf'] }
    - { role: linux-security, tags: ['linux-security'] }

    - { role: svn-install, tags: ['svn-install', 'svn'] }
    - { role: svn-deploy, vcssource: "svn+ssh://cedricg@resin.csoft.net/home/cedricg/cedric/outilsDev/ScriptsBash", 
            vcsdestdir: "{{ basedir }}/bin", tags: ['svn-deploy', 'svn'] }
    - { role: svn-deploy, vcssource: "svn+ssh://cedricg@resin.csoft.net/home/cedricg/cedric/outilsDev/envdev", 
            vcsdestdir: "{{ basedir }}/www", tags: ['svn-deploy', 'svn'] }
    - { role: svn-deploy, vcssource: "svn+ssh://cedricg@resin.csoft.net/home/cedricg/cedric/Ecritures", 
            vcsdestdir: "{{ basedir }}/Perso/Ecritures", tags: ['svn-deploy', 'svn'] }
    - { role: bin-init, tags: ['bin-init'] }

    - { role: git-install, tags: ['git-install'] }
    - { role: git-deploy, vcssource: "git@github.com:senseicoder/myscripts.git", 
            vcsdestdir: "{{ basedir }}/bin/public", tags: ['git-deploy'] }
    - { role: git-deploy, vcssource: "git@github.com:Epiconcept-Paris/infra-notes.git", 
            vcsdestdir: "{{ basedir }}/Sync/infra-notes", tags: ['git-deploy'] }
    - { role: git-deploy, vcssource: "git@github.com:Epiconcept-Paris/infra-notes.wiki.git", 
            vcsdestdir: "{{ basedir }}/Sync/infra-notes.wiki", tags: ['git-deploy'] }
    - { role: git-deploy, vcssource: "git@github.com:Epiconcept-Paris/infra-projets.wiki.git", 
            vcsdestdir: "{{ basedir }}/Sync/infra-projets.wiki", tags: ['git-deploy'] }

    - { role: sublimtext-install, tags: ['sublimtext-install'] }
    - { role: rambox-install, tags: ['rambox-install'] }
    - { role: syncthing-install, tags: ['syncthing-install'] }
    - { role: keepassx-install, tags: ['keepassx-install'] }
    - { role: kpcli-install, tags: ['kpcli-install'] }
    - { role: spotify-install, tags: ['spotify-install'] }
    - { role: mysql-shell-config, tags: ['mysql-shell-config'] }
    - { role: lamp-install, tags: ['lamp-install'] }
    - { role: docker-install, tags: ['docker-install'] }
    - { role: guake-install, tags: ['guake-install'] }
    - { role: openfortissl-install, tags: ['openfortissl-install'] }
    - { role: cps-install, tags: ['cps-install'] }
    - { role: dossiers-init, tags: ['dossiers-init'] }
    - { role: awscli-install, tags: ['awscli-install'] }
    - { role: terraform-install, tags: ['terraform-install'] }
    - { role: teamviewer-install, tags: ['teamviewer-install'] }

    - { role: etc-commit, tags: ['always'] }