---

- hosts: all
  vars:
    compte: cedric
    basedir: "/home/{{ compte }}"
    module_lang: fr_FR.UTF-8
  roles:
    - ubuntu-cleanup
    - { role: auth-init, tags: ['encours'] }
    - apt-init
    - bash-completion
    - { role: ssh-auth, tags: ['ssh-auth'] }

    - role: svn-install
    - { role: deploy-svn, vcssource: "svn+ssh://cedricg@resin.csoft.net/home/cedricg/cedric/outilsDev/ScriptsBash", vcsdestdir: "{{ basedir }}/bin" }
    - { role: deploy-svn, vcssource: "svn+ssh://cedricg@resin.csoft.net/home/cedricg/cedric/outilsDev/envdev", vcsdestdir: "{{ basedir }}/www" }

    - { role: git-install, tags: ['git-install'] }
    - { role: deploy-git, vcssource: "git@github.com:senseicoder/myscripts.git", vcsdestdir: "{{ basedir }}/bin/public" }
    - { role: deploy-git, vcssource: "git@github.com:Epiconcept-Paris/infra-notes.git", vcsdestdir: "{{ basedir }}/Sync/infra-notes", tags: ['encours'] }

    - { role: sublimtext-install, tags: ['sublimtext-install'] }
    - { role: rambox-install, tags: ['rambox-install'] }