---

- name: repository info {{ vcsdestdir }}
  shell: "svn info {{ vcsdestdir }}"
  register: svn_out
  failed_when: false

- name: repository checkout {{ vcsdestdir }}
  local_action: "shell svn co {{ vcssource }} {{ vcsdestdir }} "
  when: svn_out.rc == 1

- name: repository update {{ vcsdestdir }}
  local_action: "shell svn up {{ vcsdestdir }} "
  when: svn_out.rc == 0