---

#- subversion:
#    repo: "{{ vcssource }}"
#    dest: "{{ vcsdestdir }}"
#    checkout: no
#    update: no
#  register: out  
#- debug: var=out

- name: repository {{ vcsdestdir }}
  subversion:
    repo: "{{ vcssource }}"
    dest: "{{ vcsdestdir }}"
    force: yes
  register: out

#- debug: var=out