---

#http://linuxfr.org/users/spack/journaux/openssh-useroaming-no
- name: openssh roaming
  become: True
  become_user: root
  lineinfile: dest=/etc/ssh/ssh_config regexp="^UseRoaming " line="UseRoaming no" state=present
