---
#todo, ne marche franchement pas, faut faire le checkout à la main en fait, à revoir

- name: creation dossier si besoin
  file: 
    path: "{{ vcsdestdir }}"
    state: directory  

- name: repository info {{ vcsdestdir }}
  shell: "svn info {{ vcsdestdir }}"
  register: svn_out
  failed_when: false

- name: Add repository checkout command to ~/manuel.sh
  lineinfile:
    path: ~/manuel.sh
    line: 'svn co "{{ vcssource }}" "{{ vcsdestdir }}" 2>&1'
    insertafter: EOF
  when: svn_out.rc == 1

- name: Add repository update command to ~/manuel.sh
  lineinfile:
    path: ~/manuel.sh
    line: 'svn up "{{ vcsdestdir }}"'
    insertafter: EOF
  when: svn_out.rc == 0