---

- name: verifier la presence svn
  ansible.builtin.command: svn --version --quiet
  register: svn_install_version
  failed_when: false
  changed_when: false
  check_mode: false

- name: installation svn
  become: true
  ansible.builtin.package:
    name: subversion
    state: latest
  when: svn_install_version.rc != 0

- name: creer le dossier de configuration svn
  ansible.builtin.file:
    path: "{{ basedir }}/.subversion"
    state: directory
    mode: "0700"

- name: svn sections
  ansible.builtin.lineinfile:
    dest: "{{ basedir }}/.subversion/config"
    line: "{{ item }}"
    regexp: "^{{ item }}$" 
    create: yes 
    state: present
  with_items:
    - '[miscellany]'
    - '[auth]'

- name: svn ignore
  ansible.builtin.lineinfile:
    dest: "{{ basedir }}/.subversion/config"
    line: "global-ignores = .tags .tags_sorted_by_file *.*~ *.sublime-workspace .* *.retry" 
    insertafter: "^.miscellany." 
    regexp: "^global-ignores =" 
    create: yes 
    state: present

- name: svn store-passwords
  ansible.builtin.lineinfile:
    dest: "{{ basedir }}/.subversion/config"
    line: "store-passwords = yes" 
    insertafter: "^.auth." 
    regexp: "^store-passwords =" 
    create: yes 
    state: present
