--- 

- name: installation svn
  become: true
  package: name=subversion state=latest

- name: svn ignore
  lineinfile: 
    dest: "{{ basedir }}/.subversion/config"
    line: "global-ignores = .tags .tags_sorted_by_file *.*~ *.sublime-workspace .* *.retry" 
    insertafter: "^.miscellany." 
    regexp: "^global-ignores =" 
    create: yes 
    state: present

- name: svn store-passwords
  lineinfile: 
    dest: "{{ basedir }}/.subversion/config"
    line: "store-passwords = yes" 
    insertafter: "^.auth." 
    regexp: "^store-passwords =" 
    create: yes 
    state: present