---
- name: mercurial /etc before-commit
  become: True
  become_user: root
  command: hg commit --cwd /etc -Am "workstation role rattrapage"
  register: commande
  failed_when: commande.rc > 1
  changed_when: commande.stdout != "nothing changed"
  args:
    chdir: /etc

- name: repository partner
  become: True
  become_user: root
  apt_repository: repo='deb http://archive.canonical.com/ trusty partner' state=present
- name: repository syncthing
  become: True
  become_user: root
  apt_repository: repo='deb http://apt.syncthing.net/ syncthing release' state=present
- name: apt update et upgrade
  become: True
  become_user: root
  apt: update_cache=yes upgrade=dist force=yes
  changed_when: false
- name: bash_aliases
  copy: src=bash_aliases dest=/home/{{ compte }}/.bash_aliases owner=cedric mode=0600

- name: libs
  become: True
  become_user: root
  with_items: [ ibus, ibus-gtk, ibus-qt4 ]
  apt:
    name: '{{ item }}'
- name: outils
  become: True
  become_user: root
  with_items: [ aptitude, pwgen, sshfs, colordiff, iotop, htop, mytop, sharutils, subversion, yakuake, mercurial, git ]
  apt:
    name: '{{ item }}'
- name: communication
  become: True
  become_user: root
  with_items: [ pidgin, skype ]
  apt:
    name: '{{ item }}'
- name: réseau
  become: True
  become_user: root
  with_items: [ gufw, ssmtp, openssh-server, wakeonlan ]
  apt:
    name: '{{ item }}'
- name: internet
  become: True
  become_user: root
  with_items: [ ktorrent, nfs-common, lynx ]
  apt:
    name: '{{ item }}'
- name: video
  become: True
  become_user: root
  with_items: [ mplayer, mencoder, totem, handbrake ]
  apt:
    name: '{{ item }}'

- name: git configure
  command: git config --global push.default matching
  changed_when: false
- name: mercurial configure
  copy: src=hgrc dest=/home/{{ compte }}/.hgrc owner=cedric mode=0600

- name: installation kp cli
  shell: pip install keepassx
  become: True
  become_user: root
- name: configuration kp cli
  lineinfile: dest="{{ basedir_perso }}/.bashrc" state=present line="export KP_DB_FILE={{ basedir_perso }}/Sync/Central/trousseau.kdb"
- copy: src=files/python_keepassx_main.py dest=/usr/local/lib/python2.7/dist-packages/keepassx/main.py
  become: True
  become_user: root

- name: installation kpcli
  become: True
  become_user: root
  with_items: [ kpcli, libterm-readline-gnu-perl, libdata-password-perl ]
  apt:
    name: '{{ item }}'
- name: dépendances kpcli
  shell: cpan Clipboard Capture::Tiny

#svn
#cp ssh/* ~/.ssh/
#/usr/bin/ssh-add /home/cedric/.ssh/svnKey /home/cedric/.ssh/id_rsa

#- name: svn co bin
# subversion: repo=svn+ssh://cedricg@resin.csoft.net/home/cedricg/cedric/outilsDev/ScriptsBash/ dest={{ basedir }}/bin
# - name: svn co Coeur
#   subversion: repo=svn+ssh://cedricg@resin.csoft.net/home/cedricg/cedric/Coeur dest={{ basedir_perso }}/Coeur
#   environment:
#     LANG: C #fr_FR.UTF-8
#     LC_ALL: C #fr_FR.UTF-8
# - name: svn co Ecriture
#   subversion: repo=svn+ssh://cedricg@resin.csoft.net/home/cedricg/cedric/Ecritures dest={{ basedir_perso }}/Ecritures
#   environment:
#     LANG: en_US.UTF-8
#     LC_ALL: en_US.UTF-8

- name: mercurial /etc after-commit
  become: True
  become_user: root
  command: hg commit --cwd /etc -Am "workstation role security"
  register: commande
  failed_when: commande.rc > 1
  changed_when: commande.stdout != "nothing changed"
  args:
    chdir: /etc