--- 

- name: installation git
  become: true
  package: name=git state=latest

- set_fact: 
    dirconf: "{{ basedir }}/.config/git"

- name: fichier de configuration git
  file: path={{ dirconf }} state=directory owner={{ compte }} group={{ compte }}

- name: configuration git (ignore 1)
  lineinfile: dest="{{ dirconf }}/ignore" line="**/*.sublime-workspace" owner={{ compte }} group={{ compte }} create=yes state=present

- name: configuration git (ignore 2)
  lineinfile: dest="{{ dirconf }}/ignore" line="**/*.retry" owner={{ compte }} group={{ compte }} create=yes state=present

- name: configuration git globale
  community.general.git_config:
    name: "{{ item.name }}"
    scope: global
    value: "{{ item.value }}"
  loop:
    - name: user.email
      value: c.girard@epiconcept.fr
    - name: user.name
      value: Cédric Girard
    - name: push.default
      value: simple
