---

- name: Déployer la configuration netplan
  ansible.builtin.template:
    src: 01-network-manager-all.yaml.j2
    dest: /etc/netplan/01-network-manager-all.yaml
    owner: root
    group: root
    mode: "0600"
  become: true
  register: netplan_file

- name: Appliquer les routes via M7 (netplan apply cassé sur Ubuntu 18.04)
  ansible.builtin.command: "ip route replace {{ item }} via {{ m6network_gateway }}"
  become: true
  loop: "{{ m6network_routes }}"