---
- name: créer le dossier ssh utilisateur
  ansible.builtin.file:
    path: "{{ basedir }}/.ssh"
    state: directory
    owner: "{{ compte }}"
    group: "{{ compte }}"
    mode: "0700"

- name: clefs serveur CSoft
  ansible.builtin.known_hosts:
    path: "{{ basedir }}/.ssh/known_hosts"
    name: resin.csoft.net
    key: "resin.csoft.net {{ lookup('file', item).split(' ', 1)[1] }}"
    hash_host: true
    state: present
  loop:
    - resin.csoft.net.1.pubkey
    - resin.csoft.net.2.pubkey
