---

- apt: name=mercurial update_cache=true state=present
  become: true

- name: mercurial configure
  copy: src=hgrc dest={{ basedir }}/.hgrc owner={{ compte }} mode=0600

- name: mercurial configure
  copy: src=hgrc dest=/root/.hgrc owner=root mode=0600
  become: true
