---

- name: installation pip
  apt:
    name: python-pip
    state: latest
  become: True

- name: installation kp cli
  shell: pip install keepassx
  become: True
  changed_when: false

- name: configuration kp cli
  lineinfile: dest="{{ basedir }}/.bashrc" state=present line="export KP_DB_FILE={{ basedir }}/Sync/Central/trousseau.kdb"
- copy: src=files/python_keepassx_main.py dest=/usr/local/lib/python2.7/dist-packages/keepassx/main.py
  become: True

- name: installation kpcli
  become: True
  with_items: [ kpcli, libterm-readline-gnu-perl, libdata-password-perl ]
  apt:
    name: '{{ item }}'
- name: dépendances kpcli
  become: True
  shell: cpan Clipboard Capture::Tiny
  changed_when: false
  