# Let NetworkManager manage all devices on this system
network:
  version: 2
  ethernets:
    eno1:                          # adapte le nom de l'interface
      dhcp4: true
      routes:
        - to: 10.68.7.0/24
          via: 192.168.100.177
        - to: 10.40.9.0/24
          via: 192.168.100.177
        - to: 10.50.5.0/24
          via: 192.168.100.177
        - to: 10.40.5.0/24
          via: 192.168.100.177
