---

- name: repository partner
  become: True
  become_user: root
  apt_repository: repo='deb http://archive.canonical.com/ trusty partner' state=present

- name: autoriser i386 (pour skype)
  become: True
  become_user: root
  shell: dpkg --add-architecture i386
  changed_when: false

- name: apt update et upgrade
  become: True
  become_user: root
  apt: update_cache=yes upgrade=dist force=yes
  changed_when: false
- name: bash_aliases
  copy: src=bash_aliases dest=/home/{{ ansible_user }}/.bash_aliases owner={{ ansible_user }} mode=0600

- name: libs
  become: True
  become_user: root
  with_items: [ ibus, ibus-gtk, ibus-qt4 ]
  apt:
    name: '{{ item }}'
- name: outils
  become: True
  become_user: root
  with_items: [ aptitude, apt-transport-https, pwgen, sshfs, colordiff, iotop, htop, mytop, sharutils, subversion, yakuake, mercurial, git, python, python-pip, python-dev ]
  apt:
    name: '{{ item }}'
- name: communication
  become: True
  become_user: root
  with_items: [ pidgin, skype ]
  apt:
    name: '{{ item }}'
- name: réseau
  become: True
  become_user: root
  with_items: [ gufw, ssmtp, openssh-server, wakeonlan ]
  apt:
    name: '{{ item }}'
- name: internet
  become: True
  become_user: root
  with_items: [ ktorrent, nfs-common, lynx ]
  apt:
    name: '{{ item }}'
- name: video
  become: True
  become_user: root
  with_items: [ mplayer, mencoder, totem, handbrake ]
  apt:
    name: '{{ item }}'

#svn
#cp ssh/* ~/.ssh/
#/usr/bin/ssh-add /home/cedric/.ssh/svnKey /home/cedric/.ssh/id_rsa

#- name: svn co bin
# subversion: repo=svn+ssh://cedricg@resin.csoft.net/home/cedricg/cedric/outilsDev/ScriptsBash/ dest={{ basedir }}/bin
# - name: svn co Coeur
#   subversion: repo=svn+ssh://cedricg@resin.csoft.net/home/cedricg/cedric/Coeur dest={{ dirhome }}/Coeur
#   environment:
#     LANG: C #fr_FR.UTF-8
#     LC_ALL: C #fr_FR.UTF-8
# - name: svn co Ecriture
#   subversion: repo=svn+ssh://cedricg@resin.csoft.net/home/cedricg/cedric/Ecritures dest={{ dirhome }}/Ecritures
#   environment:
#     LANG: en_US.UTF-8
#     LC_ALL: en_US.UTF-8
