---

- name: Installer la configuration bash utilisateur
  ansible.builtin.template:
    src: bash_aliases.j2
    dest: "{{ bash_aliases_file }}"
    owner: "{{ compte }}"
    group: "{{ compte }}"
    mode: "0644"
