---

#- fail:
#    msg: à refaire en partant de la doc apt de Syncthing, en l'état ça n'a pas marché sur raspi0spdm (deb11)

- name: Télécharger la clé GPG de Syncthing avec wget
  command: wget -O /etc/apt/trusted.gpg.d/syncthing-release-key.gpg https://syncthing.net/release-key.txt
  become: yes

- name: Ajouter la clé GPG de Syncthing
  apt_key:
    file: /etc/apt/trusted.gpg.d/syncthing-release-key.gpg
  become: yes

- name: repository syncthing
  become: True
  become_user: root
  apt_repository: repo='deb http://apt.syncthing.net/ syncthing release' state=present
- name: déploiement paquet
  apt: name=syncthing update_cache=yes state=latest
  become: yes
- name: activer le service
  systemd:
    state: started
    enabled: True
    name: "{{ syncthing_service_name }}"
    daemon_reload: yes
  become: yes

- name: Lire la clé API Syncthing
  slurp:
    src: "{{ syncthing_api_key_file }}"
  register: api_key_file

- set_fact:
    syncthing_key: "{{ api_key_file.content | b64decode | trim }}"
#    shares:
#      - folder_id: "central"
#        label: "Central"
#        path: "{{ basedir }}/Sync/Central"
#      - folder_id: "Epiconcept"
#        label: "Epiconcept"
#        path: "{{ basedir }}/Sync/Epiconcept"
#      - folder_id: "pixel_4a_5g_k9km-photos"
#        label: "Caméra Pixel4A"
#        path: "{{ basedir }}/Sync/Photos/Pixel4A"

- name: Récupérer la configuration actuelle de Syncthing
  uri:
    url: "{{ syncthing_url }}/rest/system/config"
    method: GET
    headers:
      X-API-Key: "{{ syncthing_key }}"
    return_content: yes
  register: syncthing_config

- name: Ajouter les appareils à la configuration
  set_fact:
    updated_config: "{{ syncthing_config.content | from_json }}"

- name: Identifier les appareils Syncthing existants
  set_fact:
    syncthing_existing_device_ids: "{{ updated_config.devices | default([]) | map(attribute='deviceID') | list }}"

- name: Identifier les appareils Syncthing manquants
  set_fact:
    syncthing_missing_devices: "{{ syncthing_devices | rejectattr('device_id', 'in', syncthing_existing_device_ids) | list }}"

- name: Ajouter les nouveaux appareils dans la configuration
  set_fact:
    updated_config: "{{ updated_config | combine({'devices': updated_config.devices + [{'deviceID': item.device_id, 'name': item.device_name, 'addresses': ['dynamic'], 'compression': 'metadata', 'introducer': false, 'skipIntroductionRemovals': false}]}) }}"
  loop: "{{ syncthing_missing_devices }}"
  changed_when: syncthing_missing_devices | length > 0

#- name: Ajouter chaque partage à la configuration avec tous les appareils
#  set_fact:
#    updated_config: "{{ updated_config | combine({'folders': updated_config.folders + [{'id': item.folder_id, 'label': item.label, 'path': item.path, 'type': 'readwrite', 'devices': devices | map(attribute='device_id') | list, 'rescanIntervalS': 3600, 'fsWatcherEnabled': true, 'fsWatcherDelayS': 10}]}) }}"
#  loop: "{{ shares }}"

#- debug: var=updated_config

- name: Mettre à jour la configuration dans Syncthing
  uri:
    url: "{{ syncthing_url }}/rest/system/config"
    method: POST
    headers:
      X-API-Key: "{{ syncthing_key }}"
      Content-Type: "application/json"
    body: "{{ updated_config | to_json }}"
    status_code: 200
  when:
    - syncthing_missing_devices | length > 0
    - not ansible_check_mode
  register: syncthing_config_update

- name: Redémarrer Syncthing pour appliquer la nouvelle configuration
  uri:
    url: "{{ syncthing_url }}/rest/system/restart"
    method: POST
    headers:
      X-API-Key: "{{ syncthing_key }}"
  when:
    - syncthing_config_update is defined
    - syncthing_config_update is changed
    - not ansible_check_mode
