---

- name: mercurial /etc auto-commit
  command: hg commit --cwd /etc -Am "workstation role security"
  register: out
  failed_when: out.rc > 1
  changed_when: out.stdout != "nothing changed"
  become: true
  args:
    chdir: /etc
