export LANG='fr_FR.UTF-8'

alias ls='ls --color=auto'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias antidote='/opt/Druide/Antidote8/Programmes64/Antidote8'
