---
#source: https://docs.docker.com/engine/installation/linux/ubuntulinux/

- set_fact:
    compose_version: 1.6.0

- apt_repository: repo='deb http://get.docker.io/ubuntu docker main' state=absent
- file: path=/etc/apt/sources.list.d/docker.list state=absent
- apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main' state=present
- apt_key: keyserver=p80.pool.sks-keyservers.net id=58118E89F3A912897C070ADBF76221572C52609D

- apt: name=lxc-docker state=absent
  register: lxcdocker_removed
- service: name=docker enabled=no state=stopped
  when: lxcdocker_removed.changed
- file: path=/var/lib/docker state=absent #sinon grosse charge IO quand on passe à docker-engine
  when: lxcdocker_removed.changed

- shell: uname -r
  register: uname_r
  changed_when: false

- shell: uname -s
  register: uname_s
  changed_when: false

- shell: uname -m
  register: uname_m
  changed_when: false

- apt: name={{ item }} update_cache=yes state=present
  with_items: ["apt-transport-https", "ca-certificates", "linux-image-extra-{{ uname_r.stdout }}", "docker-engine"]

- get_url: 
    url="https://github.com/docker/compose/releases/download/{{ compose_version }}/docker-compose-{{ uname_s.stdout }}-{{ uname_m.stdout }}" 
    dest="/usr/local/bin/docker-compose" mode=0755

- service: name=docker enabled=yes state=started

# sublim text

- set_fact:
    subl_path_dest: "/home/cedric/.config/sublime-text-3/Installed Packages/Package Control.sublime-package"

- name: configuration Sublim Text
  get_url: >
    url="https://packagecontrol.io/Package%20Control.sublime-package" 
    dest="{{ subl_path_dest }}"
    owner={{ compte }} group={{ compte }}

# git 

- name: fichier de configuration git
  file: path={{ basedir_perso }}/.config/git/ state=directory owner={{ compte }} group={{ compte }}
- name: configuration git (ignore 1)
  lineinfile: dest={{ basedir_perso }}/.config/git/ignore line="**/*.sublime-workspace" owner={{ compte }} group={{ compte }} create=yes state=present
- name: configuration git (ignore 2)
  lineinfile: dest={{ basedir_perso }}/.config/git/ignore line="**/*.retry" owner={{ compte }} group={{ compte }} create=yes state=present
- name: configuration svn (ignore)
  lineinfile: dest=/etc/subversion/config line="global-ignores = .tags .tags_sorted_by_file *.*~ *.sublime-workspace .* *.retry" regexp="^global-ignores =" owner={{ compte }} group={{ compte }} create=yes state=present
  become: yes
  become_user: root

#https://help.github.com/articles/caching-your-github-password-in-git/
- shell: git config --global credential.helper 'cache --timeout=36000'
  become: yes
  become_user: "{{ compte }}"
  changed_when: false