---

- name: installer aptitude
  become: yes
  package: name=aptitude state=latest

- name: repo epiconcept
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64,all] https://apt.epiconcept.fr/prep/ {{ ansible_distribution_release }} main"
    filename: epiconcept
    state: present
  become: true

- name: apt update/upgrade
  become: yes
  apt: update_cache=true upgrade=full
