---

# 20241004 plus utile ? 
#- name: repository partner
#  become: True
#  apt_repository:
#    repo: "deb http://archive.canonical.com/ {{ ansible_distribution_release }} partner"
#    state: present

- name: installation paquets
  become: True
  apt:
    name: '{{ item }}'
  with_items: [ 
    #libs
    ibus, ibus-gtk, 
    #obsolète 20.04 : ibus-qt4,
    #outils
    vim, tree, glances, apt-transport-https, pwgen, sshfs, colordiff, iotop, htop, sharutils, subversion, python3-dev, guake, rlwrap,
    #communication
    chromium-browser,
    #réseau
    gufw, ssmtp, openssh-server, wakeonlan, cifs-utils, curl,
    #graphismes
    gimp,
    #internet
    nfs-common, lynx, traceroute, whois,
    #ebooks et docs
    calibre, pandoc, texlive,
    #video
    mplayer, mencoder, totem, handbrake,mkvtoolnix,
    #lamp
    mysql-client, mysql-server, apache2, php, php-curl,
    #gnome
    chrome-gnome-shell,
    #data
    jq, vym,
    #dev
    subversion, git
    ]
