---

- name: repository partner
  become: True
  apt_repository: repo='deb http://archive.canonical.com/ bionic partner' state=present

- name: installation paquets
  become: True
  apt:
    name: '{{ item }}'
  with_items: [ 
    #libs
    ibus, ibus-gtk, ibus-qt4,
    #outils
    vim, tree, glances, apt-transport-https, pwgen, sshfs, colordiff, iotop, htop, mytop, sharutils, subversion, python-dev, guake, rlwrap,
    #communication
    pidgin, chromium-browser,
    #réseau
    gufw, ssmtp, openssh-server, wakeonlan, cifs-utils,
    #internet
    nfs-common, lynx,
    #video
    mplayer, mencoder, totem, handbrake,
    #lamp
    mysql-client,mysql-server,apache2,php,php-curl,
    #gnome
    chrome-gnome-shell
    ]