---

# 20241004 plus utile ? 
#- name: repository partner
#  become: True
#  apt_repository:
#    repo: "deb http://archive.canonical.com/ {{ ansible_distribution_release }} partner"
#    state: present

- name: installation paquets
  become: true
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - colordiff
      - curl
      - glances
      - htop
      - iotop
      - jq
      - lynx
      - openssh-server
      - pwgen
      - sharutils
      - traceroute
      - tree
      - vim
      - wakeonlan
      - whois
    state: present
